# =====================================
# HYPRLOCK — MINIMAL TTY (1.5x)
# =====================================

$font = JetBrains Mono Nerd Font

general {
    hide_cursor = true
    no_fade_in = true
}

animations {
    enabled = true
    bezier = linear,1,1,0,0

    animation = fadeIn,1,3,linear
    animation = fadeOut,1,3,linear
    animation = inputFieldDots,1,1,linear
}

background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 2

    brightness = 0.25
    contrast = 1.05
}

shape {
    size = 100%,100%
    color = rgba(000000cc)
}

# -------------------------
# CLOCK
# -------------------------

label {
    text = [$TIME]
    font_family = $font
    font_size = 20
    color = rgba(e8e8e8ff)

    position = 0,-80
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] date +"%a %d %b %Y"
    font_family = $font
    font_size = 33
    color = rgba(999999ff)

    position = 0,-15
    halign = center
    valign = center
}

# -------------------------
# PROMPT
# -------------------------

label {
    text = [ unlock ]
    font_family = $font
    font_size = 33
    color = rgba(88ff88ff)

    position = -273,105
    halign = center
    valign = center
}

input-field {
    size = 450,68

    position = 93,105
    halign = center
    valign = center

    rounding = 0
    outline_thickness = 1

    inner_color = rgba(00000000)
    outer_color = rgba(88ff8833)

    font_family = $font
    font_color = rgba(e8e8e8ff)

    placeholder_text = _
    placeholder_color = rgba(88ff88aa)

    hide_input = false
    dots_text_format = *
    dots_size = 0.45
    dots_spacing = 0.33

    fade_on_empty = false

    check_color = rgba(88ff88ff)
    fail_color = rgba(ff6666ff)

    fail_text = auth failed
}

label {
    text = EN | RU
    onclick = hyprctl switchxkblayout all next

    font_size = 21
    color = rgba(666666ff)

    position = 0,218
    halign = center
    valign = center
}
